name: PvPBots
version: '${project.version}'
main: com.swirb.pvpbots.PvPBots
api-version: 1.18
authors: [ Swirb ]
description: bots that are smart and beat you in pvp
website: https://www.youtube.com/channel/UCqdWbVRctQBMrZQUjuvYjug

commands:
  bots:
    description: bot stuff