package com.swirb.pvpbots.basicallyGarbage.ai;

public class Setting {

    public final double GENE_DISABLE_CHANCE;
    public final double MUTATION_ADD_NODE_CHANCE;
    public final double MUTATION_ADD_CONNECTION_CHANCE;
    public final double MUTATION_CHANGE_CONNECTION_WEIGHT;
    public final double MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM;
    public final double MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM_RANGE;
    public final double MUTATION_CHANGE_CONNECTION_WEIGHT_ERROR;
    public final double COMP_DISTANCE_WEIGHT_DISJOINT;
    public final double COMP_DISTANCE_WEIGHT_EXCESS;
    public final double COMP_DISTANCE_WEIGHT_AVG_WEIGHT;
    public final double COMP_DISTANCE_SPECIES_MAX;
    public final double GENERATION_DEATH_PERCENTAGE;
    public final double GENERATION_COPY_CHANCE;
    public final int GENERATION_FAILS_MAX;

    public Setting() {
        this.GENE_DISABLE_CHANCE = 0.75D;
        this.MUTATION_ADD_NODE_CHANCE = 0.03D;
        this.MUTATION_ADD_CONNECTION_CHANCE = 0.05D;
        this.MUTATION_CHANGE_CONNECTION_WEIGHT = 0.8D;
        this.MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM = 0.1D;
        this.MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM_RANGE = 5.0D;
        this.MUTATION_CHANGE_CONNECTION_WEIGHT_ERROR = 0.25D;
        this.COMP_DISTANCE_WEIGHT_DISJOINT = 1.0D;
        this.COMP_DISTANCE_WEIGHT_EXCESS = 1.0D;
        this.COMP_DISTANCE_WEIGHT_AVG_WEIGHT = 0.4D;
        this.COMP_DISTANCE_SPECIES_MAX = 0.8D;
        this.GENERATION_DEATH_PERCENTAGE = 0.9D;
        this.GENERATION_COPY_CHANCE = 0.25D;
        this.GENERATION_FAILS_MAX = 10;
    }

    public Setting(Double GENE_DISABLE_CHANCE,
                   Double MUTATION_ADD_NODE_CHANCE,
                   Double MUTATION_ADD_CONNECTION_CHANCE,
                   Double MUTATION_CHANGE_CONNECTION_WEIGHT,
                   Double MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM,
                   Double MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM_RANGE,
                   Double MUTATION_CHANGE_CONNECTION_WEIGHT_ERROR,
                   Double COMP_DISTANCE_WEIGHT_DISJOINT,
                   Double COMP_DISTANCE_WEIGHT_EXCESS,
                   Double COMP_DISTANCE_WEIGHT_AVG_WEIGHT,
                   Double COMP_DISTANCE_SPECIES_MAX,
                   Double GENERATION_DEATH_PERCENTAGE,
                   Double GENERATION_COPY_CHANCE,
                   Integer GENERATION_FAILS_MAX) {
        this.GENE_DISABLE_CHANCE = GENE_DISABLE_CHANCE == null ? 0.75D : GENE_DISABLE_CHANCE;
        this.MUTATION_ADD_NODE_CHANCE = MUTATION_ADD_NODE_CHANCE == null ? 0.03D : MUTATION_ADD_NODE_CHANCE;
        this.MUTATION_ADD_CONNECTION_CHANCE = MUTATION_ADD_CONNECTION_CHANCE == null ? 0.05D : MUTATION_ADD_CONNECTION_CHANCE;
        this.MUTATION_CHANGE_CONNECTION_WEIGHT = MUTATION_CHANGE_CONNECTION_WEIGHT == null ? 0.8D : MUTATION_CHANGE_CONNECTION_WEIGHT;
        this.MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM = MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM == null ? 0.1D : MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM;
        this.MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM_RANGE = MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM_RANGE == null ? 5.0D : MUTATION_CHANGE_CONNECTION_WEIGHT_RANDOM_RANGE;
        this.MUTATION_CHANGE_CONNECTION_WEIGHT_ERROR = MUTATION_CHANGE_CONNECTION_WEIGHT_ERROR == null ? 0.25D : MUTATION_CHANGE_CONNECTION_WEIGHT_ERROR;
        this.COMP_DISTANCE_WEIGHT_DISJOINT = COMP_DISTANCE_WEIGHT_DISJOINT == null ? 1.0D : COMP_DISTANCE_WEIGHT_DISJOINT;
        this.COMP_DISTANCE_WEIGHT_EXCESS = COMP_DISTANCE_WEIGHT_EXCESS == null ? 1.0D : COMP_DISTANCE_WEIGHT_EXCESS;
        this.COMP_DISTANCE_WEIGHT_AVG_WEIGHT = COMP_DISTANCE_WEIGHT_AVG_WEIGHT == null ? 0.4D : COMP_DISTANCE_WEIGHT_AVG_WEIGHT;
        this.COMP_DISTANCE_SPECIES_MAX = COMP_DISTANCE_SPECIES_MAX == null ? 0.8D : COMP_DISTANCE_SPECIES_MAX;
        this.GENERATION_DEATH_PERCENTAGE = GENERATION_DEATH_PERCENTAGE == null ? 0.9D : GENERATION_DEATH_PERCENTAGE;
        this.GENERATION_COPY_CHANCE = GENERATION_COPY_CHANCE == null ? 0.25D : GENERATION_COPY_CHANCE;
        this.GENERATION_FAILS_MAX = GENERATION_FAILS_MAX == null ? 10 : GENERATION_FAILS_MAX;
    }
}
